version: '3.9'

services:
  mysql:
    image: mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
    ports:
      - "127.0.0.1:8080:80"
    